manager/config/routes.rb
Manager::Application.routes.draw do
  devise_for :users

  match '/analytics' => 'analytics#index'

  
  resources :datacenter
  root :to => 'home#index'
  

end

manager/app/models/cluster.rb
class Cluster < ActiveRecord::Base
  validates_presence_of :name, :type_id
  belongs_to :datacenter
  has_many :servers

end

manager/app/models/datacenter.rb
class Datacenter < ActiveRecord::Base
  validates_presence_of :name
  has_many :clusters
  has_one :type
  has_one :location
end

manager/app/models/datalog.rb
class Datalog < ActiveRecord::Base
  belongs_to :server
end

manager/app/models/location.rb
class Location < ActiveRecord::Base
  validates_presence_of :address, :city, :state, :zipcode, :country
  belongs_to :datacenter
end

manager/app/models/server.rb
class Server < ActiveRecord::Base
  validates_presence_of :name, :ipaddress, :model, :cluster_id
  belongs_to :cluster
  has_many :datalogs
end

manager/app/models/type.rb
class Type < ActiveRecord::Base
  validates_presence_of :name
  belongs_to :cluster
end

manager/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

manager/app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
  end
end

manager/app/controllers/cluster_controller.rb
class ClusterController < ApplicationController
end

manager/app/controllers/datacenter_controller.rb
class DatacenterController < ApplicationController
  def index
  end
  
  def create
    def create
      @datacenter = Datacenter.new(params[:datacenter])
      @location = @datacenter.locations.build(params[:location])
      if @datacenter.save
        redirect_to :action => 'index'
      else
        render :action => 'new'
      end
    end
  end
  
  def new
    @location = Location.new
    @datacenter = Datacenter.new
  end
  
  def edit
  end
  
  def show 
  end
  
  def show 
  end
  
  def update
  end
  
  def destroy
  end
end

manager/app/controllers/datalog_controller.rb
class DatalogController < ApplicationController
end

manager/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

manager/app/controllers/server_controller.rb
class ServerController < ApplicationController
end

manager/app/helpers/analytics_helper.rb
module AnalyticsHelper
end

manager/app/helpers/application_helper.rb
module ApplicationHelper
end

manager/app/helpers/cluster_helper.rb
module ClusterHelper
end

manager/app/helpers/datacenter_helper.rb
module DatacenterHelper
end

manager/app/helpers/datalog_helper.rb
module DatalogHelper
end

manager/app/helpers/home_helper.rb
module HomeHelper
end

manager/app/helpers/server_helper.rb
module ServerHelper
end

manager/app/views/layouts/_create_sidebar.html.erb
<div class='span3'>
  <div class='well sidebar-nav'>
    <ul class='nav-list nav'>
      <li class='nav-header'>
        Create new Records
      </li>
      <li>
        <%= link_to "Datacenter", new_datacenter_path %>
      </li>
      <li>
        <a href='/new/cluster'>Cluster</a>
      </li>
      <li>
        <a href='/new/server'>Server</a>
      </li>
      <li>
        <a href='/new/datalog'>Datalog</a>
      </li>
      <li class='nav-header'>
        <a href='/import'>Import Config File</a>
      </li>
    </ul>
  </div>
</div>

manager/app/views/layouts/_footer.html.erb
<hr />
<div class='container-fluid'>
  <p>
    Power Smart Labs  &copy; 2012
    <br />
    <a href='/support'>Support</a>
    <a href='/contact'>Contact</a>
    <a href='http://powersmartlabs.com' target='_blank'>Company</a>
  </p>
</div>

manager/app/views/layouts/_navigation.html.erb
<%= link_to "PowerSmart Manager", root_path, :class => 'brand' %>
<div class="nav-collapse">

<ul class="nav">
    <li>
      <a href='/analytics'>Analytics</a>
    </li>
    
    <li>
      <a href='/charts'>Charts</a>
    </li>
    <li>
      <a href='/power'>Power</a>
    </li>

<ul class='nav pull-right'>
    <% if user_signed_in? %>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to('Edit account', edit_user_registration_path) %>
      </li>
      <li class="divider-vertical"></li>
      <li>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      </li>
    <% else %>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to 'Login', new_user_session_path %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to 'Sign up', new_user_registration_path %>
      </li>
    <% end %>
</ul>
</div>

manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Manager" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application", :media => 'all' %>
    
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container-fluid">
         <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container-fluid">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">×</a>
              <%= msg %>
          </div>
        <% end %>
      <%= yield %>
      </div>   
      <footer>
          <%= render 'layouts/footer'%>
      </footer>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>